version: '3'

services:

  zenko:
    image: zenko/cloudserver:8.2.7
    ports:
      - 8000:8000
    environment:
      - SCALITY_ACCESS_KEY_ID=test-key
      - SCALITY_SECRET_ACCESS_KEY=test-secret
      - S3BACKEND=mem
      - ENDPOINT=zenko

  arangodb:
    image: arangodb:3.7.11
    ports:
      - 8529:8529
    environment:
      - ARANGO_ROOT_PASSWORD=password
      - ARANGODB_OVERRIDE_DETECTED_TOTAL_MEMORY=100m

  hazelcast:
    image: hazelcast/hazelcast:4.1.5
    ports:
      - 5701:5701
      - 8088:8080
