package com.innerfriends.userprofilepicture.domain;

public interface UserProfilePictureRepository {

    UserProfilePictureSaved storeNewUserProfilePicture(NewUserProfilePicture newUserProfilePicture) throws UserProfilePictureRepositoryException;

    ContentUserProfilePicture getContent(UserProfilePictureIdentifier userProfilePictureIdentifier) throws UserProfilePictureUnknownException, UserProfilePictureRepositoryException;

}
